FROM uatschitchun/stretch-s6-base

WORKDIR /tmp

RUN apt-get update && \
	apt-get install --no-install-recommends -y \
	software-properties-common \
	dirmngr \
	apt-transport-https \
	gnupg

RUN apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8 \
 && add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirror.23media.de/mariadb/repo/10.3/debian stretch main'

RUN echo deb https://packages.e-tobi.net/vdr-experimental stretch base vdr-multipatch addons > /etc/apt/sources.list.d/e-tobi.list \
 && echo deb-src https://packages.e-tobi.net/vdr-experimental stretch base vdr-multipatch addons >> /etc/apt/sources.list.d/e-tobi.list \
 && apt-key adv --recv-keys --keyserver keyring.debian.org --recv-keys 041390BC

# && gpg --keyserver keyring.debian.org --recv-keys 041390BC && gpg --armor --export 041390BC | apt-key add -

# && apt-get update -qq && \
#	apt-get install -qy e-tobi-keyring

#COPY etobi /etc/apt/preferences.d/etobi

RUN echo Package: * > /etc/apt/preferences.d/etobi \
 && echo Pin: release o=e-tobi.net >> /etc/apt/preferences.d/etobi \
 && echo Pin-Priority: 1000 >> /etc/apt/preferences.d/etobi

#RUN ls -l /etc/apt/preferences.d/etobi

RUN apt-get update


RUN apt-cache policy vdr-plugin-restfulapi vdr-plugin-vnsiserver vdr-plugin-vdrmanager
#
ENTRYPOINT ["/init"]
